line-length = 79
target-version = "py310"

[lint]
select = ["ALL"]
ignore = [
    "ANN",
    "B008",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D300",
    "ERA001",
    "FIX002",
    "I001",
    "INP001",
    "N803",
    "N804",
    "N806",
    "N812",
    "PLR0913",
    "PLW2901",
    "Q000",
    "Q001",
    "Q002",
    "RET504",
    "RUF012",
    "SLF001",
    "TD002",
    "TD003",
    "TID252",
    "UP015",
]

[format]
quote-style = "single"
