#!/bin/bash
for file in *.mp4; do
  [ -e "$file" ] || { echo "No .mp4 files found."; exit 1; }
  rm palette.png
  ffmpeg -y -i $file -vf "fps=10,scale=320:-1:flags=lanczos,palettegen" palette.png
  ffmpeg -y -i $file -i palette.png -filter_complex "fps=10,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse" $file.gif
done
