#!/bin/bash
CONFIGURATION_PATHS="
.jupyter
.ruff.toml
"
SCRIPT_PATHS="
clean-notebooks
roll-dice
"

SCRIPTS_FOLDER=~/.scripts
if [ ! -e $SCRIPTS_FOLDER ]; then
    mkdir $SCRIPTS_FOLDER
fi

cd $(dirname "$0")

for X in $CONFIGURATION_PATHS; do
    cp $X ~ -r
done

for X in $SCRIPT_PATHS; do
    cp $X $SCRIPTS_FOLDER
    chmod a+x $SCRIPTS_FOLDER/$X
done

if command -v dnf; then
    X=dnf
elif command -v apt; then
    X=apt
elif command -v brew; then
    X=brew
fi

source ~/.bashrc
v
pip install -U \
    ruff

echo ok
