#!/bin/bash
command -v dconf > /dev/null && dconf load / < gnome.properties

CONFIGURATION_PATHS="
.eslintrc.js
.stylelintrc.js
"
SCRIPT_PATHS="
bleach
boot-windows
browse-media
check-battery
check-ports.py
clip-file
clip-ip
clip-key
disable-backlight
disable-wakeup
download-mp3
encrypt-password
gif
prepare-playlist.py
rank-sizes
sp
see-tree
set-brightness
sort-music.py
sort-music.sh
sort-photos.py
transfer
update-submodules
"

SCRIPTS_FOLDER=~/.scripts
if [ ! -e $SCRIPTS_FOLDER ]; then
    mkdir $SCRIPTS_FOLDER
fi

cd $(dirname "$0")

for X in $CONFIGURATION_PATHS; do
    cp $X ~ -r
done

for X in $SCRIPT_PATHS; do
    cp $X $SCRIPTS_FOLDER
    chmod a+x $SCRIPTS_FOLDER/$X
done

if command -v dnf; then
    X=dnf
elif command -v apt; then
    X=apt
elif command -v brew; then
    X=brew
fi
command -v npm || sudo $X install npm -y
command -v shellcheck || sudo $X install shellcheck -y
command -v hadolint || sudo $X install hadolint -y

source ~/.bashrc
v
pip install -U \
    ansible-lint \
    yamllint
npm install -g \
    @biomejs/biome \
    htmlhint \
    markdownlint-cli2

mkdir ~/.config/bleachbit -p
cp bleachbit.ini ~/.config/bleachbit

mkdir ~/.config/fontconfig -p
cp fonts.conf ~/.config/fontconfig

echo ok
