#!/bin/bash
CONFIGURATION_FOLDERS="
.jupyter
"
CONFIGURATION_PATHS="
.eslintrc.js
.gvimrc
.ruff.toml
"
SCRIPT_PATHS="
clean-notebooks
roll-dice
"

SCRIPTS_FOLDER=~/.scripts
if [ ! -e $SCRIPTS_FOLDER ]; then
    mkdir $SCRIPTS_FOLDER
fi

cd $(dirname "$0")

for X in $CONFIGURATION_PATHS; do
    cp $X ~
    echo 'cp '$X ~
done

for X in $SCRIPT_PATHS; do
    cp $X $SCRIPTS_FOLDER
    chmod a+x $SCRIPTS_FOLDER/$X
    echo 'cp '$X $SCRIPTS_FOLDER
done

if command -v dnf; then
    X=dnf
elif command -v apt; then
    X=apt
elif command -v brew; then
    X=brew
fi
command -v npm || sudo $X install npm -y

source ~/.bashrc
v
pip install -U \
    ruff
npm install -g \
    bash-language-server \
    fixjson \
    htmlhint \
    markdownlint \
    stylelint stylelint-config-standard
command -v yamllint || sudo $X install yamllint -y

echo ok
