#!/bin/bash
SCRIPT_PATHS="
bleach
boot-windows
browse-photos
check-battery
check-ports.py
clip-file
clip-ip
clip-key
disable-backlight
disable-wakeup
download-mp3
encrypt-password
prepare-playlist.py
rank-sizes
sp
see-tree
set-brightness
sort-music.py
sort-music.sh
sort-photos.py
transfer
update-submodules
"

SCRIPTS_FOLDER=~/.scripts
if [ ! -e $SCRIPTS_FOLDER ]; then
    mkdir $SCRIPTS_FOLDER
fi

cd $(dirname "$0")

for X in $SCRIPT_PATHS; do
    cp $X $SCRIPTS_FOLDER
    chmod a+x $SCRIPTS_FOLDER/$X
    echo 'cp '$X $SCRIPTS_FOLDER
done

if command -v dnf; then
    X=dnf
elif command -v apt; then
    X=apt
elif command -v brew; then
    X=brew
fi
command -v gvim || sudo $X install vim-X11 -y

source ~/.bashrc
v
pip install -U \
    ansible-lint
command -v hadolint || sudo $X install hadolint -y

mkdir -p ~/.config/bleachbit
cp bleachbit.ini ~/.config/bleachbit

command -v dconf && dconf load / < gnome.properties

echo ok
