#!/bin/bash
update() {
    BRANCH_NAME=$(git branch --show-current)
    if [ -z "$BRANCH_NAME" ]; then
        BRANCH_NAME=$(git branch --list develop)
        if [ -z "$BRANCH_NAME" ]; then
            BRANCH_NAME=$(git branch --list master)
            if [ -z "$BRANCH_NAME" ]; then
                BRANCH_NAME=$(git branch --list main)
            fi
        fi
    fi
    git checkout $BRANCH_NAME
    git pull
    git remote prune origin
}
git submodule init
git submodule update
update

find . -type f -name .git | while read G_FOLDER; do
    X_FOLDER=${G_FOLDER/\.git/}
    pushd $X_FOLDER > /dev/null
    update
    popd > /dev/null
done
